#!/usr/bin/env fish
# Re-dump tide/fish color universal vars into fedora-setup/fish/universal_vars.fish
# Run this whenever you tweak your prompt/colors and want to commit the new state.

set -l out (dirname (status -f))/../fish/universal_vars.fish
set out (realpath $out)

printf "%s\n" "# Auto-generated by scripts/dump-fish-vars.fish" > $out
printf "%s\n" "# Applied by install.sh --only fish" >> $out
printf "%s\n" "# Regenerate after tweaking: fish scripts/dump-fish-vars.fish" >> $out
printf "\n" >> $out

for var in (set -U --names)
    if not string match -qr "^(tide_|fish_color_|fish_pager_color_|fish_greeting)" -- $var
        continue
    end
    set -l vals $$var
    if test (count $vals) -eq 0
        printf "set -U %s\n" $var >> $out
    else
        printf "set -U %s " $var >> $out
        for v in $vals
            printf "%s " (string escape -- $v) >> $out
        end
        printf "\n" >> $out
    end
end

echo "wrote "(count (cat $out))" lines -> $out"
