# Auto-generated by scripts/dump-fish-vars.fish
# Applied by install.sh --only fish
# Regenerate after tweaking: fish scripts/dump-fish-vars.fish

set -U fish_color_autosuggestion 6c7086 
set -U fish_color_cancel f38ba8 
set -U fish_color_command 89b4fa 
set -U fish_color_comment 7f849c --italics 
set -U fish_color_cwd f9e2af 
set -U fish_color_end fab387 
set -U fish_color_error f38ba8 
set -U fish_color_escape eba0ac 
set -U fish_color_gray 6c7086 
set -U fish_color_host 89b4fa 
set -U fish_color_host_remote a6e3a1 
set -U fish_color_keyword f38ba8 
set -U fish_color_normal cdd6f4 
set -U fish_color_operator f5c2e7 
set -U fish_color_option a6e3a1 
set -U fish_color_param f2cdcd 
set -U fish_color_quote a6e3a1 
set -U fish_color_redirection f5c2e7 
set -U fish_color_search_match --background=313244 
set -U fish_color_selection --background=313244 
set -U fish_color_status f38ba8 
set -U fish_color_user 94e2d5 
set -U fish_color_valid_path --underline 
set -U fish_pager_color_completion cdd6f4 
set -U fish_pager_color_description 6c7086 
set -U fish_pager_color_prefix f5c2e7 --bold --underline 
set -U fish_pager_color_progress 6c7086 
set -U fish_pager_color_selected_background --background=313244 
set -U tide_aws_bg_color normal 
set -U tide_aws_color FF9900 
set -U tide_aws_icon  
set -U tide_bun_bg_color normal 
set -U tide_bun_color FBF0DF 
set -U tide_bun_icon 󰳓 
set -U tide_character_color 5FD7FF 
set -U tide_character_color_failure FF5F5F 
set -U tide_character_icon ❯ 
set -U tide_character_vi_icon_default ❯ 
set -U tide_character_vi_icon_replace ▶ 
set -U tide_character_vi_icon_visual V 
set -U tide_cmd_duration_bg_color C4A000 
set -U tide_cmd_duration_color 000000 
set -U tide_cmd_duration_decimals 0 
set -U tide_cmd_duration_icon
set -U tide_cmd_duration_threshold 3000 
set -U tide_context_always_display false 
set -U tide_context_bg_color 444444 
set -U tide_context_color_default D3D7CF 
set -U tide_context_color_root FFFF00 
set -U tide_context_color_ssh D3D7CF 
set -U tide_context_hostname_parts 1 
set -U tide_crystal_bg_color normal 
set -U tide_crystal_color FFFFFF 
set -U tide_crystal_icon  
set -U tide_direnv_bg_color normal 
set -U tide_direnv_bg_color_denied normal 
set -U tide_direnv_color D7AF00 
set -U tide_direnv_color_denied FF0000 
set -U tide_direnv_icon ▼ 
set -U tide_distrobox_bg_color normal 
set -U tide_distrobox_color FF00FF 
set -U tide_distrobox_icon 󰆧 
set -U tide_docker_bg_color normal 
set -U tide_docker_color 2496ED 
set -U tide_docker_default_contexts default colima 
set -U tide_docker_icon  
set -U tide_elixir_bg_color normal 
set -U tide_elixir_color 4E2A8E 
set -U tide_elixir_icon  
set -U tide_gcloud_bg_color normal 
set -U tide_gcloud_color 4285F4 
set -U tide_gcloud_icon 󰊭 
set -U tide_git_bg_color 4E9A06 
set -U tide_git_bg_color_unstable C4A000 
set -U tide_git_bg_color_urgent CC0000 
set -U tide_git_color_branch 000000 
set -U tide_git_color_conflicted 000000 
set -U tide_git_color_dirty 000000 
set -U tide_git_color_operation 000000 
set -U tide_git_color_staged 000000 
set -U tide_git_color_stash 000000 
set -U tide_git_color_untracked 000000 
set -U tide_git_color_upstream 000000 
set -U tide_git_icon
set -U tide_git_truncation_length 24 
set -U tide_git_truncation_strategy
set -U tide_go_bg_color normal 
set -U tide_go_color 00ACD7 
set -U tide_go_icon  
set -U tide_java_bg_color normal 
set -U tide_java_color ED8B00 
set -U tide_java_icon  
set -U tide_jobs_bg_color 2E3436 
set -U tide_jobs_color 4E9A06 
set -U tide_jobs_icon
set -U tide_jobs_number_threshold 1 
set -U tide_kubectl_bg_color normal 
set -U tide_kubectl_color 326CE5 
set -U tide_kubectl_icon 󱃾 
set -U tide_left_prompt_items pwd git newline character 
set -U tide_left_prompt_prefix  
set -U tide_left_prompt_separator_diff_color  
set -U tide_left_prompt_separator_same_color  
set -U tide_left_prompt_suffix  
set -U tide_nix_shell_bg_color normal 
set -U tide_nix_shell_color 7EBAE4 
set -U tide_nix_shell_icon  
set -U tide_node_bg_color 4E9A06 
set -U tide_node_color 000000 
set -U tide_node_icon
set -U tide_os_bg_color 000000 
set -U tide_os_color FFFFFF 
set -U tide_os_icon
set -U tide_php_bg_color normal 
set -U tide_php_color 617CBE 
set -U tide_php_icon  
set -U tide_private_mode_bg_color normal 
set -U tide_private_mode_color FFFFFF 
set -U tide_private_mode_icon 󰗹 
set -U tide_prompt_add_newline_before true 
set -U tide_prompt_color_frame_and_connection 6C6C6C 
set -U tide_prompt_color_separator_same_color 949494 
set -U tide_prompt_icon_connection ' ' 
set -U tide_prompt_min_cols 34 
set -U tide_prompt_pad_items true 
set -U tide_prompt_transient_enabled true 
set -U tide_pulumi_bg_color normal 
set -U tide_pulumi_color F7BF2A 
set -U tide_pulumi_icon  
set -U tide_pwd_bg_color 3465A4 
set -U tide_pwd_color_anchors E4E4E4 
set -U tide_pwd_color_dirs E4E4E4 
set -U tide_pwd_color_truncated_dirs BCBCBC 
set -U tide_pwd_icon
set -U tide_pwd_icon_home
set -U tide_pwd_icon_unwritable
set -U tide_pwd_markers .git .bzr .citc .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform CMakeLists.txt Cargo.toml composer.json go.mod package.json stack.yaml 
set -U tide_python_bg_color 4E9A06 
set -U tide_python_color 000000 
set -U tide_python_icon
set -U tide_right_prompt_items status cmd_duration context jobs node python time 
set -U tide_right_prompt_prefix  
set -U tide_right_prompt_separator_diff_color  
set -U tide_right_prompt_separator_same_color  
set -U tide_right_prompt_suffix  
set -U tide_ruby_bg_color normal 
set -U tide_ruby_color B31209 
set -U tide_ruby_icon  
set -U tide_rustc_bg_color normal 
set -U tide_rustc_color F74C00 
set -U tide_rustc_icon  
set -U tide_shlvl_bg_color normal 
set -U tide_shlvl_color d78700 
set -U tide_shlvl_icon  
set -U tide_shlvl_threshold 1 
set -U tide_status_bg_color 2E3436 
set -U tide_status_bg_color_failure CC0000 
set -U tide_status_color 4E9A06 
set -U tide_status_color_failure FFFF00 
set -U tide_status_icon ✔ 
set -U tide_status_icon_failure ✘ 
set -U tide_terraform_bg_color normal 
set -U tide_terraform_color 844FBA 
set -U tide_terraform_icon 󱁢 
set -U tide_time_bg_color 2E3436 
set -U tide_time_color 666666 
set -U tide_time_format '%H:%M:%S' 
set -U tide_toolbox_bg_color normal 
set -U tide_toolbox_color 613583 
set -U tide_toolbox_icon  
set -U tide_vi_mode_bg_color_default normal 
set -U tide_vi_mode_bg_color_insert normal 
set -U tide_vi_mode_bg_color_replace normal 
set -U tide_vi_mode_bg_color_visual normal 
set -U tide_vi_mode_color_default 949494 
set -U tide_vi_mode_color_insert 87AFAF 
set -U tide_vi_mode_color_replace 87AF87 
set -U tide_vi_mode_color_visual FF8700 
set -U tide_vi_mode_icon_default D 
set -U tide_vi_mode_icon_insert I 
set -U tide_vi_mode_icon_replace R 
set -U tide_vi_mode_icon_visual V 
set -U tide_zig_bg_color normal 
set -U tide_zig_color F7A41D 
set -U tide_zig_icon  
